### PR TITLE
Updated Error object hierarchy so all error inherit from AvroError.

### PR DESCRIPTION
**Pull request by blake-nicholson**
- lib/errors.js
  
  Cleaned up the various Avro...Error classes so they inherit from
  a single AvroError class that contains the common code.  Removed
  duplicated code from the various implementation classes.

### CODE REVIEW

**Comment by vkareh** [comment]
Looks much cleaner, thanks - that `this.fieldPath = []` in the `AvroDataValidationError` leaves me wondering though... It seems the library never uses that feature - all it does is print out something like `"Data [%j] is not null"`, but it would be interesting to assign it the schema path to it - although that can be done in the message itself, rather than the `fieldPath` array. Thoughts?

**Comment by kyriesent** [comment]
Thanks for doing this. Looks like he really liked cmd+c and cmd+v...

**Comment by blake-nicholson** [comment]
@vkareh, take a look at DatumWriter.writeRecord in lib/io.js.  It writes out each field and populates fieldPath if an error occurs while attempting to write the data for a particular field.

**Comment by vkareh** [comment]
Ah - finally see it - thanks! :+1:

**Pull request merged**
